const mongoose = require("mongoose");

const AdmissionFormSchema = new mongoose.Schema({
  fullName: String,
  dob: String,
  gender: String,
  category: String,
  nationality: String,
  aadhaar: String,
  contactNumber: String,
  email: String,
  permanentAddress: String,
  correspondenceAddress: String,
  tenthPercent: String,
  twelfthPercent: String,
  yearOfPassing: String,
  boardName: String,
  entranceExam: String,
  rollNumber: String,
  scoreRank: String,
  degree: String,
  branch1: String,
  branch2: String,
  branch3: String,
  studyMode: String,
  fatherName: String,
  fatherOccupation: String,
  fatherContact: String,
  motherName: String,
  motherOccupation: String,
  motherContact: String,
  familyIncome: String,
  parentEmail: String,
  counselingType: String,
  counselingMode: String,
  counselingDate: String,
  counselorName: String,
  remarks: String,
  applicantDate: String,
  parentDate: String,
}, { timestamps: true });

module.exports = mongoose.model("AdmissionForm", AdmissionFormSchema);
