const mongoose = require("mongoose");

const careerFormSchema = new mongoose.Schema({
  fullName: String,
  classGrade: String,
  section: String,
  dob: String,
  gender: String,
  contactNumber: String,
  email: String,
  schoolName: String,
  address: String,
  performance: String,
  favoriteSubjects: String,
  difficultSubjects: String,
  examScores: String,
  coCurricular: String,
  activities: String,
  interests: [String],
  hobbies: String,
  skills: String,
  hasCareerInMind: String,
  preferredCareer: String,
  streamOptions: String,
  reasons: String, 
  
  guidanceReceived: String,
  preferredColleges: String,
  counselingType: String,
  counselingMode: String,
  counselingDate: String,
  counselorName: String,
  remarks: String,
  counselorFindings: String,
  recommendedPath: String,
  interventions: [String],
  followUpDate: String,
  counselorSignature: String,
  counselorDate: String,
  declarationStudentSign: String,
  declarationParentSign: String,
}, { timestamps: true });

module.exports = mongoose.model("CareerForm", careerFormSchema);
